from django.conf.urls.defaults import *
from MP100.fotos.views import *

urlpatterns = patterns('',
    #url(r'^$', index, name='main_user'),
    #url(r'^logout/$', logout_view, name='logout_view'),
    #url(r'^editar_perfil/$',
    #    editar_perfil, name = 'editar_perfil'),
    #url(r'^perfil/$', ver_perfil, name = 'ver_perfil'),
    #url(r'^perfil/(?P<object_id>\d+)/$', perfil_publico,
    #    name = 'fotos_perfil_publico'),
    #url(r'^enviar_mensaje/(?P<object_id>\d+)/$', enviar_mensaje,
    #    name='fotos_enviar_mensaje'),
    #url(r'^mensaje_enviado/(?P<object_id>\d+)/$', mensaje_enviado,
    #    name='fotos_mensaje_enviado'),
    #url(r'^amigos/(?P<object_id>\d+)/$', ver_amigos_public,
    #    name='fotos_ver_amigos_public'),
    #url(r'^fotos/(?P<object_id>\d+)/$', ver_fotos_public,
    #    name="fotos_ver_fotos_public"),

    #url(r'^buscar/$', buscar, name='fotos_buscar_usuarios'),
    #url(r'^solicitar/$', solicitud, name='fotos_solicitud'),
    #url(r'^solicitud_enviada/$', solicitud_enviada,
    #    name="fotos_solicitud_enviada"),
    #url(r'^solicitud_innecesaria/$', solicitud_innecesaria,
    #    name="fotos_solicitud_innecesaria"),
    #url(r'^mis_fotos/$', ver_fotos, name="fotos_ver_fotos"),
    #url(r'^mis_votos/$', ver_votos, name="fotos_ver_votos"),
    #url(r'^subir_fotos/$', subir_fotos, name="fotos_subir_fotos"),
    #url(r'^subir_fotos/exito/$', subir_fotos_exito,
    #    name="fotos_subir_fotos_exito"),
    #url(r'^borrar_foto/$', borrar_foto, name='fotos_borrar_foto'),
    #url(r'^borrar_comentario/$', borrar_comentario,
    #    name='fotos_borrar_comentario'),
    #url(r'^buscar_fotos/$', buscar_fotos, name="fotos_buscar_fotos"),
    #url(r'^ver_solicitudes/$', ver_solicitudes, name="fotos_ver_solicitudes"),
    #url(r'^aceptar_solicitud/$', aceptar_solicitud,
    #    name="fotos_aceptar_solicitud"),
    #url(r'^eliminar_solicitud/$', eliminar_solicitud,
    #    name="fotos_eliminar_solicitud"),
    #url(r'^amigos/$', ver_amigos, name='fotos_amigos'),
    #url(r'^eliminar_amigo/$', eliminar_amigo, name='fotos_eliminar_amigo'),
    #url(r'^amigo_eliminado/$', amigo_eliminado, name='fotos_amigo_eliminado'),
    #url(r'^enviar_invitacion/$', enviar_invitacion,
    #    name='fotos_enviar_invitacion'),
    #url(r'^invitacion_enviada/$', invitacion_enviada,
    #    name='fotos_invitacion_enviada'),
    #url(r'^noticias/(?P<tema>\w+)/$', noticias, name='fotos_noticias'),
    #url(r'^noticia/(?P<object_id>\d+)/$', ver_noticia,
    #    name='fotos_ver_noticia'),
    #url(r'^ganadores/$', ver_ganadores, name='fotos_ver_ganadores'),
    #url(r'^ayuda/$', opciones_ayuda, name='fotos_ayuda'),
    #url(r'^ayuda/(?P<opcion>\w+)/$', ayuda_detail, name='fotos_ayuda_detail'),
    #url(r'^proxima_temporada/$', buscar_fotos_prox_temp,
    #    name="fotos_buscar_fotos_prox_temp"),
    
    
    #JARUFE
    url(r'^json_me_gusta/(?P<foto_id>\d+)/$', json_me_gusta, 
        name='json_me_gusta'),
    #url(r'^json_comentar_perfil/(?P<usuario_id>\d+)/(?P<texto>[\w|\s]+)$', 
    #    json_comentar_perfil, name='json_comentar_perfil'),
    #url(r'^json_add_favoritos/(?P<foto_id>\d+)/$', json_add_favoritos, 
    #    name='json_add_favoritos'),
    #url(r'^(?P<user>\w+)/(?P<foto_id>\d+)/(?P<mis_fotos>\d+)/$', navegar_foto, 
    #    name='fotos_navegar_foto'),   
    #url(r'^(?P<object_id>\d+)/(?P<foto_id>\d+)/$', navegar_foto_publico,
    #    name = 'fotos_navegar_foto_publico'),

)
